name: CI
 
on:
  push:
    paths-ignore:
      - 'README.md'

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
          
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build PDF
        env:
          APP: lualatex-for-my-cv
          YML: .devcontainer/docker-compose.yml
        run: |
          docker-compose -f ${YML} up -d
          docker-compose -f ${YML} exec -T ${APP} make cv.pdf

      - name: Create Git Tag
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        id: tag
        run: |
          echo "v-$(TZ=Asia/Tokyo date +%Y%m%d-%H%M%S)" > TAG_NAME
          git tag $(cat TAG_NAME)
          git push origin $(cat TAG_NAME)
          echo "::set-output name=release_tag::$(cat TAG_NAME)"

      - name: Create Release & upload asset
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: ./output/cv.pdf
          draft: false
          prerelease: false
