name: Build and release pdf

on:
  push:
    tags:
      - 'v-*-*'

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build pdf
        env:
          IMAGE: ghcr.io/shunk031/lualatex-for-my-cv:latest
        run: |
          docker run --rm -v $(pwd):/workdir ${IMAGE} make cv.pdf

      - name: Create Release & upload asset
        id: create_release-upload_assets
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ./output/cv.pdf
          draft: false
          prerelease: false
